get http://localhost:3003/todos/?dueDate=2021-1-21
###
get http://localhost:3003/todos/2/

###
get http://localhost:3003/agenda/?date=2021-12-12

###
post http://localhost:3003/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

###
put http://localhost:3003/todos/3/
Content-Type: application/json

{ "status": "DONE" }

###
 delete http://localhost:3003/todos/2/